apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <CA_CERTIFICATE>
    server: https://<K8S_API_SERVER>
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
    namespace: default
  name: my-context
current-context: my-context
users:
- name: my-user
  user:
    client-certificate-data: <USER_CERTIFICATE>
    client-key-data: <USER_KEY>
