---
- name: Launch EC2 instance in a VPC
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather information about any instance with a tag key Name and value Example
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": Example