---
- name: Launch EC2 instance in a VPC
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch an EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
        count: 1
        tags:
          K8s: k8s_masters
        state: started
        wait: true
      register: ec2

