---
- name: Delete EC2 instance
  hosts: k8s_masters
  gather_facts: no
  user: ubuntu
  tasks:
    - name: Delete instance created for tests
      amazon.aws.ec2_instance:
        state: absent
        instance_ids: "{{ ec2.instance_ids }}"
        wait: true
