- name: Run a ping command and a small k8s deployment
  hosts: k8s_masters
  gather_facts: yes
  user : ubuntu
  vars:
    ansible_python_interpreter: auto
  tasks:
    - name: Check connectivity with echo
      command: echo "Hello, World!"
      register: output

    - name: Print command output
      debug:
        var: output.stdout
    
    - name: Verify connectivity
      ping:

    - name: Deploy Nginx pod in the namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: nginx-pod
            namespace: my-app-namespace
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
      become: yes

    - name: Wait for the Nginx pod to be running
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: my-app-namespace
        label_selectors:
          - app=nginx-pod
      register: pod_info

    - name: Check pod status until it's running
      wait_for:
        timeout: 60
        delay: 5
        state: present
        path: /tmp
      until: pod_info.resources[0].status.phase == "Running"

    - name: Verify Nginx pod is running
      shell: kubectl get pods -n my-app-namespace -o wide
      register: nginx_status
      become: yes

    - name: Print Nginx pod status
      debug:
        var: nginx_status.stdout_lines